class FFI::UCTags
  type ffi_library = Module & FFI::Library
  
  VERSION: String
  COMMAND: Array[String]
  
  attr_accessor self.ffi_module: Module
  
  def self.ffi_const: (Object::name name) -> bot
  def self.call: (_ToS lib_path, _ToS header_path, ?namespace: Module) -> ffi_library
  
  attr_accessor library: ffi_library
  def initialize: (ffi_library lib) -> void
  
  @prefix: Array[untyped]
  def prefix: (*top prefixes) -> void
  @suffix: Array[untyped]
  def suffix: (*top suffixes) -> void
  @args: Array[untyped]
  def <<: (top arg) -> void
  
  @receiver: untyped?
  @method: Object::name?
  
  def typeref: (Hash[String, String] fields) -> FFI::Type
  def open: (?top receiver, Object::name? method) -> void
  def close: -> void
end
