# Select stubs
module FFI
  class Enum
  end
  
  module Library
  end
  type library = Module & Library
  
  class Struct
    def self.layout: (*untyped spec) -> StructLayout
  end
  
  class StructLayout
  end
  
  class Type
  end
end
